CREATE TABLE EMP(-- 创建emp表
	ID INT PRIMARY KEY AUTO_INCREMENT,-- 添加主键和自动增长约束
	NAME VARCHAR(32) NOT NULL,-- 添加非空约束
	AGE INT,
	DEP_NAME VARCHAR(30),-- 部门名称
	DEP_LOCATION VARCHAR(30)-- 部门地址
);
INSERT INTO EMP VALUES (NULL,'张三',20,'研发部','广州');
INSERT INTO EMP VALUES (NULL,'李四',21,'研发部','广州');
INSERT INTO EMP VALUES (NULL,'王五',20,'研发部','广州');
INSERT INTO EMP VALUES (NULL,'老王',20,'销售部','深圳');
INSERT INTO EMP VALUES (NULL,'大王',20,'销售部','深圳');
INSERT INTO EMP VALUES (NULL,'小王',18,'销售部','深圳');
SELECT * FROM EMP
-- 数据有重复

-- 拆分表
 -- 解决方案 ：分成2张表
 -- 创建部门表
 CREATE TABLE DEPARTMENT(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	DEP_NAME VARCHAR(21),
	DEP_LOCATION VARCHAR (20)
 );
 
 -- 创建员工表
 CREATE TABLE EMPLOYEE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(20),
	AGE INT,
	DEP_ID INT,-- 外键对应主表的主键
	CONSTRAINT EMP_DEPT_FK FOREIGN KEY (DEP_ID) REFERENCES DEPARTMENT(ID)
	-- 设置外键
 );
 # 添加2个部门
 INSERT INTO DEPARTMENT VALUES (NULL,'研发部','广州'),(NULL,'销售部','深圳');
 #添加员工 dep_id 表示员工所在部门
 INSERT INTO EMPLOYEE (NAME,AGE,DEP_ID) VALUES('张三',20,1);
 INSERT INTO EMPLOYEE (NAME,AGE,DEP_ID) VALUES('李四',21,1);
 INSERT INTO EMPLOYEE (NAME,AGE,DEP_ID) VALUES('王五',20,2);
 INSERT INTO EMPLOYEE (NAME,AGE,DEP_ID) VALUES('大王',22,2);
 INSERT INTO EMPLOYEE (NAME,AGE,DEP_ID) VALUES('小王',18,2);
 SELECT * FROM DEPARTMENT
 SELECT * FROM EMPLOYEE
 
 
 # 外键约束 foreign key  constraint 外键名称 foreign key 外键列名称 reference主表名称（主表列名称）
DROP TABLE EMP
DROP TABLE DEPARTMENT
 DROP TABLE EMPLOYEE
 # 删除外键 
 ALTER TABLE EMPLOYEE DROP FOREIGN KEY EMP_DEPT_FK;
 
 # 创建表后 添加外键 设置级联更新和级联删除（可以一起用也可以分开用 不用逗号分隔）
 -- 级联更新 在外键后 加上 NO UPDATE CASCADE  级联的意思是 在修改关联的表时 
 -- 另外一个表也跟着修改 级联删除 NO DELETE CASCADE 
 -- 删除 意思是 在删除一个表列的同时 另一个表的列也跟着删除
  ALTER TABLE EMPLOYEE ADD CONSTRAINT EMP_DEPT_FK FOREIGN KEY(DEP_ID) REFERENCES DEPARTMENT (ID) NO UPDATE CASCADES;
 
 