
START TRANSACTION -- 开启事物 start transaction 

ROLLBACK 	-- 事物回滚	rollback
	
COMMIT 		-- 提交事物	commit

CREATE DATABASE IF  NOT EXISTS DB1;
CREATE TABLE STUDENT( -- 学生表
	STUDENT_ID INT PRIMARY KEY,
	SNAME VARCHAR(32) NOT NULL,
	SAGE VARCHAR(34),
	SSEX VARCHAR(4)
);
SELECT * FROM department;
ALTER TABLE STUDENT MODIFY SAGE INT;
ALTER TABLE STUDENT CHARACTER SET ;
ALTER DATABASE DB1 CHARACTER SET UTF8;
CREATE TABLE Teacher( -- 教师表
	teacher_id INT PRIMARY KEY,
	Tname VARCHAR(23) NOT NULL
);
CREATE TABLE COURSE( -- 课程表
	COURSE_ID INT PRIMARY KEY,
	CNAME VARCHAR(32) NOT NULL,
	teacher_id INT,
	CONSTRAINT teacher_course_fk FOREIGN KEY (teacher_id)  REFERENCES teacher(teacher_id)
);

CREATE TABLE sc(-- 成绩表
	sc_id INT PRIMARY KEY,
	COURSE_ID INT NOT NULL,
	score VARCHAR(32),
	CONSTRAINT sc_course_fk FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
);
ALTER TABLE SC MODIFY SCORE INT;
DELETE FROM student WHERE STUDENT_ID=1

INSERT INTO STUDENT (STUDENT_ID,SNAME,SAGE,SSEX) VALUES (1,"刘一",18,'男');

start transaction 	-- 开启事物
	
rollback		-- 事物回滚 

commit 			-- 提交事物
 